# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70fcf96a87e48086e8027d87796e92146c6235f9750d84691b14087f2c6bbb68115a3c82e53717fe5f0faa8b8fbce81baec2dc72aac20cb53e9cd4b4fc5fa58

test:
  secret_key_base: 52f75d7214e2d79ca0f806a598177f0f316755c38bc681236d430227c1a50f96d427aa1b711c71c12780807114e769a85e0fe130e0bd73dde3baf0e69b0c353f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
